---
title: "Trabalho final da disciplina de Fluxo de Trabalho Reprodutível com Dados Ecológicos em R"
subtitle: ""
author: "Thays Klitzke"
format:
  gfm:                   # gera GitHub Flavored Markdown
    toc: true
    number-sections: false
    df-print: default
output-file: README.md   # <- importante: o resultado será o README.md
editor: visual
freeze: auto
---

> **Resumo**\
> Este é um projeto desenvolvido com dados fictícios que buscou alcançar os objetivos de aprendizado da disciplina Fluxo de Trabalho Reprodutível com Dados Ecológicos em R, ministrada no Programa de Pós-Graduação em Ecologia e Conservação da biodiversidade da Universidade Estadual de Santa Cruz pelos docentes Diogo S. B. Rocha e Hernani Ramos em setembro de 2025.
>
> O objetivo do projeto foi verificar a influência de variáveis abióticas em atributos morfofisiológicos de indivíduos jovens de *Euterpe edulis* em regiões de altitude no Sul da Bahia.

|  |  |
|----|----|
| **Responsável pela Criação** | Thays Klitzke |
| **Data da Criação/Análise** | Outubro de 2025 |
| **Software Utilizado** | R (Linguagem de Programação) e pacotes: `readr`,  `dplyr`,  `tibble`, `tidyverse`, `lubridate`, `patchwork`, `terra`, `sf`, `ggplot2`. |
| **Licença de Uso (do Mapa Gerado)** | \[Ex: CC BY-NC 4.0 (Creative Commons Atribuição-Não Comercial) ou Nenhuma Restrição\] |
| **Contato** | thays.klisan\@gmail.com |

Os dados de altitude podem ser baixados no site do Banco de Dados Geomorfométricos do Brasil ([TOPODATA](http://www.dsr.inpe.br/topodata/acesso.php)).
